Repository depromeet/critix-server, pull requests merged in 2025-03, with the labels that each got.

#38 feat : ChatGPT Azure SDK 세팅
  build.gradle
  src/main/java/depromeet/onepiece/feedback/command/application/exception/FeedbackChatGPTErrorException.java
  src/main/java/depromeet/onepiece/feedback/command/application/exception/FeedbackCommandExceptionCode.java
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/AzureService.java
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/ChatGPTConstants.java
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/ChatGPTProperties.java
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/FeedbackService.java
  src/main/java/depromeet/onepiece/feedback/command/presentation/FeedbackCommandController.java
  src/main/java/depromeet/onepiece/feedback/command/presentation/response/FeedbackResponse.java
  src/main/resources/application.yml
Labels: ✨ Feat

#41 feat : pdf 파일 이미지 슬라이싱 구현
  build.gradle
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/FeedbackService.java
  src/main/java/depromeet/onepiece/file/command/infrastructure/ObjectStorageFileUploader.java
Labels: ✨ Feat

#43 feat : ncp에서 이미지링크 가져오기
  src/main/java/depromeet/onepiece/file/command/infrastructure/PresignedUrlGenerator.java
Labels: ✨ Feat

#39 feat: Google OAuth2 로그인 구현
  build.gradle
  src/main/java/depromeet/onepiece/common/auth/application/dto/AuthAttributes.java
  src/main/java/depromeet/onepiece/common/auth/application/dto/GoogleAuthAttributes.java
  src/main/java/depromeet/onepiece/common/auth/application/handler/CustomAuthenticationFailureHandler.java
  src/main/java/depromeet/onepiece/common/auth/application/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/depromeet/onepiece/common/auth/application/jwt/TokenInjector.java
  src/main/java/depromeet/onepiece/common/auth/application/jwt/TokenResult.java
  src/main/java/depromeet/onepiece/common/auth/application/service/AuthService.java
  src/main/java/depromeet/onepiece/common/auth/application/service/CustomOAuth2UserService.java
  src/main/java/depromeet/onepiece/common/auth/application/service/OAuth2UserDetailsService.java
  src/main/java/depromeet/onepiece/common/auth/application/service/RefreshTokenService.java
  src/main/java/depromeet/onepiece/common/auth/domain/CustomOAuth2User.java
  src/main/java/depromeet/onepiece/common/auth/domain/CustomUserDetails.java
  src/main/java/depromeet/onepiece/common/auth/domain/RefreshToken.java
  src/main/java/depromeet/onepiece/common/auth/domain/RefreshTokenRepository.java
  src/main/java/depromeet/onepiece/common/auth/infrastructure/RefreshTokenMongoRepository.java
  src/main/java/depromeet/onepiece/common/auth/infrastructure/RefreshTokenRepositoryImpl.java
  src/main/java/depromeet/onepiece/common/auth/infrastructure/SecurityProperties.java
  src/main/java/depromeet/onepiece/common/auth/infrastructure/jwt/JwtTokenProvider.java
  src/main/java/depromeet/onepiece/common/auth/infrastructure/jwt/JwtTokenResolver.java
  src/main/java/depromeet/onepiece/common/auth/infrastructure/jwt/TokenProperties.java
  src/main/java/depromeet/onepiece/common/auth/presentation/LoginController.java
  src/main/java/depromeet/onepiece/common/auth/presentation/exception/AlreadyRegisteredUserException.java
  src/main/java/depromeet/onepiece/common/auth/presentation/exception/AuthExceptionCode.java
  src/main/java/depromeet/onepiece/common/auth/presentation/exception/AuthenticationRequiredException.java
  src/main/java/depromeet/onepiece/common/auth/presentation/exception/RefreshTokenInvalidException.java
  src/main/java/depromeet/onepiece/common/config/SecurityConfig.java
  src/main/java/depromeet/onepiece/user/command/domain/UserCommandRepository.java
  src/main/java/depromeet/onepiece/user/command/infrastructure/UserCommandMongoRepository.java
  src/main/java/depromeet/onepiece/user/command/infrastructure/UserCommandRepositoryImpl.java
  src/main/java/depromeet/onepiece/user/domain/OAuthProviderType.java
  src/main/java/depromeet/onepiece/user/domain/User.java
  src/main/java/depromeet/onepiece/user/query/domain/UserQueryRepository.java
  src/main/java/depromeet/onepiece/user/query/exception/UserCommandExceptionCode.java
  src/main/java/depromeet/onepiece/user/query/exception/UserNotFoundException.java
  src/main/java/depromeet/onepiece/user/query/infrastructure/UserQueryMongoRepository.java
  src/main/java/depromeet/onepiece/user/query/infrastructure/UserQueryRepositoryImpl.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/templates/login.html
Labels: ✨ Feat

#45 feat : 목 api 3개 개발, mongodb 직렬화 역직렬화 구현
  aiflow-scheduler.puml
  src/main/java/depromeet/onepiece/common/config/SwaggerConfig.java
  src/main/java/depromeet/onepiece/common/config/WebMvcConfig.java
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/ChatGPTService.java
  src/main/java/depromeet/onepiece/feedback/command/presentation/FeedbackCommandController.java
  src/main/java/depromeet/onepiece/feedback/command/presentation/response/FeedbackResponse.java
  src/main/java/depromeet/onepiece/feedback/command/presentation/response/OverallFeedbackResponse.java
  src/main/java/depromeet/onepiece/feedback/command/presentation/response/RecentFeedbackListResponse.java
  src/main/java/depromeet/onepiece/feedback/command/presentation/response/RemainCountResponse.java
Labels: ✨ Feat

#52 chore: nginx 설정 docker-compose.yml 경로 수정
  .github/workflows/DeployToDev.yml
  infra/development/docker/docker-compose.yml
  infra/development/nginx/nginx.conf
  src/main/java/depromeet/onepiece/common/auth/presentation/LoginController.java
Labels: 🧹 Chore

#55 feat : 피드백 디테일 로직 구현
  build.gradle
  src/main/java/depromeet/onepiece/common/config/WebMvcConfig.java
  src/main/java/depromeet/onepiece/feedback/command/presentation/FeedbackCommandController.java
  src/main/java/depromeet/onepiece/feedback/domain/EvaluationDetail.java
  src/main/java/depromeet/onepiece/feedback/domain/Feedback.java
  src/main/java/depromeet/onepiece/feedback/domain/FeedbackContent.java
  src/main/java/depromeet/onepiece/feedback/domain/FeedbackDetail.java
  src/main/java/depromeet/onepiece/feedback/domain/FeedbackPerPage.java
  src/main/java/depromeet/onepiece/feedback/domain/OverallEvaluation.java
  src/main/java/depromeet/onepiece/feedback/domain/ProjectEvaluation.java
  src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryService.java
  src/main/java/depromeet/onepiece/feedback/query/application/exception/FeedbackNotFoundException.java
  src/main/java/depromeet/onepiece/feedback/query/application/exception/FeedbackQueryExceptionCode.java
  src/main/java/depromeet/onepiece/feedback/query/domain/FeedbackQueryRepository.java
  src/main/java/depromeet/onepiece/feedback/query/infrastructure/FeedbackMongoRepository.java
  src/main/java/depromeet/onepiece/feedback/query/infrastructure/FeedbackQueryRepositoryImpl.java
Labels: ✨ Feat

#56 feat : chatGPT 요청 구현
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/AzureService.java
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/ChatGPTConstants.java
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/FeedbackService.java
  src/main/java/depromeet/onepiece/feedback/command/presentation/FeedbackCommandController.java
  src/main/java/depromeet/onepiece/file/command/presentation/FileUploadController.java
Labels: ✨ Feat

#59 fix : 이미지 해상도 줄이기
  src/main/java/depromeet/onepiece/file/command/infrastructure/ObjectStorageFileUploader.java
Labels: ⚒️ Fix

#62 fix : mock 응답 수정
  src/main/java/depromeet/onepiece/feedback/command/presentation/FeedbackCommandController.java
  src/main/java/depromeet/onepiece/feedback/domain/ProjectEvaluation.java
Labels: ⚒️ Fix

#63 fix : mock 응답 수정
  src/main/java/depromeet/onepiece/feedback/command/presentation/FeedbackCommandController.java
  src/main/java/depromeet/onepiece/feedback/domain/Feedback.java
  src/main/java/depromeet/onepiece/feedback/domain/ProcessType.java
  src/main/java/depromeet/onepiece/feedback/domain/ProjectEvaluation.java
Labels: ⚒️ Fix

#69 refactor: SSL 인증서 발급 및 쿠키 cross-domain 설정
  infra/development/docker/docker-compose.yml
  infra/development/nginx/nginx.conf
  src/main/java/depromeet/onepiece/common/auth/application/jwt/TokenInjector.java
  src/main/java/depromeet/onepiece/common/config/SecurityConfig.java
  src/main/java/depromeet/onepiece/common/config/SwaggerConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: ♻️ Refactor

#72 fix: 개발 서버 CORS 이슈 픽스 및 docker-compose.yml strip_components 값 변경
  .github/workflows/DeployToDev.yml
  src/main/java/depromeet/onepiece/common/config/SecurityConfig.java
Labels: ⚒️ Fix

#68 refactor : 피드백 entity, 응답 수정
  src/main/java/depromeet/onepiece/feedback/command/presentation/FeedbackCommandController.java
  src/main/java/depromeet/onepiece/feedback/domain/FeedbackContent.java
  src/main/java/depromeet/onepiece/feedback/domain/FeedbackContentDetail.java
Labels: ♻️ Refactor

#76 fix: critix.kr:3000 CORS 허용
  src/main/java/depromeet/onepiece/common/config/SecurityConfig.java
Labels: ⚒️ Fix

#78 fix: 코드 포맷팅 CI 에러 해결
  src/main/java/depromeet/onepiece/common/config/SecurityConfig.java
Labels: ⚒️ Fix

#74 feat : 전체 피드백 목록 반환
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/FeedbackCommandMongoRepository.java
  src/main/java/depromeet/onepiece/feedback/command/presentation/FeedbackCommandController.java
  src/main/java/depromeet/onepiece/feedback/command/presentation/response/RecentFeedbackListResponse.java
  src/main/java/depromeet/onepiece/feedback/domain/Feedback.java
  src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryService.java
  src/main/java/depromeet/onepiece/feedback/query/application/exception/FeedbackQueryExceptionCode.java
  src/main/java/depromeet/onepiece/feedback/query/domain/FeedbackQueryRepository.java
  src/main/java/depromeet/onepiece/feedback/query/infrastructure/FeedbackQueryMongoRepository.java
  src/main/java/depromeet/onepiece/feedback/query/infrastructure/FeedbackQueryRepositoryImpl.java
  src/main/java/depromeet/onepiece/feedback/query/presentation/FeedbackQueryController.java
  src/main/java/depromeet/onepiece/feedback/query/presentation/response/RecentFeedbackListResponse.java
  src/main/java/depromeet/onepiece/file/command/domain/FileDocumentRepository.java
  src/main/java/depromeet/onepiece/file/command/exception/FileCommandExceptionCode.java
  src/main/java/depromeet/onepiece/file/command/exception/FileNotFoundException.java
  src/main/java/depromeet/onepiece/file/command/infrastructure/FileDocumentMongoRepository.java
  src/main/java/depromeet/onepiece/file/command/infrastructure/FileDocumentRepositoryImpl.java
  src/main/java/depromeet/onepiece/file/command/infrastructure/ObjectStorageFileUploader.java
Labels: ✨ Feat

#85 feat: 어노테이션 기반 현재 로그인 사용자 ID 주입 및 로그인 사용자 반환 API
  src/main/java/depromeet/onepiece/common/auth/annotation/CurrentUserId.java
  src/main/java/depromeet/onepiece/common/auth/application/jwt/TokenFilter.java
  src/main/java/depromeet/onepiece/common/auth/infrastructure/jwt/TokenProvider.java
  src/main/java/depromeet/onepiece/common/auth/resolver/CurrentUserArgumentResolver.java
  src/main/java/depromeet/onepiece/common/config/SecurityConfig.java
  src/main/java/depromeet/onepiece/common/config/WebMvcConfig.java
  src/main/java/depromeet/onepiece/user/domain/User.java
  src/main/java/depromeet/onepiece/user/query/application/CurrentUserIdService.java
  src/main/java/depromeet/onepiece/user/query/application/UserQueryService.java
  src/main/java/depromeet/onepiece/user/query/domain/UserQueryRepository.java
  src/main/java/depromeet/onepiece/user/query/exception/UserCommandExceptionCode.java
  src/main/java/depromeet/onepiece/user/query/exception/UserNotAuthenticatedException.java
  src/main/java/depromeet/onepiece/user/query/infrastructure/UserQueryRepositoryImpl.java
  src/main/java/depromeet/onepiece/user/query/presentation/UserQueryController.java
  src/main/java/depromeet/onepiece/user/query/presentation/response/UserResponse.java
Labels: ✨ Feat, ♻️ Refactor

#92 refactor: 개발 서버 배포 시 헬스 체크 스크립트 추가
  .github/workflows/DeployToDev.yml
Labels: 🧹 Chore, ♻️ Refactor

#95 fix : 피드백 전체 목록에서 파일 이름 복호화하게 변경
  src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryFacadeService.java
  src/main/java/depromeet/onepiece/file/query/application/FileQueryService.java
  src/main/java/depromeet/onepiece/file/query/infrastructure/FileQueryMongoRepository.java
  src/main/java/depromeet/onepiece/file/query/infrastructure/FileQueryRepository.java
  src/main/java/depromeet/onepiece/file/query/infrastructure/FileQueryRepositoryImpl.java
Labels: ⚒️ Fix

#98 feat: prometheus 기반 리소스 모니터링 시스템 구축
  .github/workflows/DeployToDev.yml
  build.gradle
  infra/development/docker/monitoring-docker-compose.yml
  monitoring/prometheus/prometheus.rules.yml
  monitoring/prometheus/prometheus.yml
  src/main/resources/application.yml
Labels: ✨ Feat, 🧹 Chore

#110 fix : 포트폴리오 응답 파일 제목 추가
  src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandFacadeService.java
  src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandService.java
  src/main/java/depromeet/onepiece/feedback/domain/Feedback.java
  src/main/java/depromeet/onepiece/feedback/query/presentation/FeedbackQueryController.java
Labels: ⚒️ Fix

#114 fix : 포트폴리오 페이지 피드백 응답 수정
  src/main/java/depromeet/onepiece/feedback/domain/EditPair.java
  src/main/java/depromeet/onepiece/feedback/domain/PageFeedbackContent.java
  src/main/java/depromeet/onepiece/feedback/query/presentation/FeedbackQueryController.java
Labels: ⚒️ Fix

#105 feat : NCP Cloud Function Trigger 파일 업로드
  src/main/java/depromeet/onepiece/file/command/infrastructure/ObjectStorageFileUploader.java
Labels: ✨ Feat

#112 feat : NCP Action 코드 추가
  infra/ncp/TextExtractAction.py
Labels: ✨ Feat

#122 feat : 프로젝트 피드백 프롬프트, 스키마 정리
  src/main/java/depromeet/onepiece/feedback/command/application/ChatGPTConstants.java
Labels: ✨ Feat

#126 fix: 개발 서버 kafka connection 이슈 픽스
  infra/development/docker/docker-compose.yml
  infra/development/docker/kafka-docker-compose.yml
Labels: ⚒️ Fix

#127 feat: 로그아웃 API 구현
  src/main/java/depromeet/onepiece/common/auth/application/service/AuthService.java
  src/main/java/depromeet/onepiece/common/auth/application/service/RefreshTokenService.java
  src/main/java/depromeet/onepiece/common/auth/presentation/AuthController.java
Labels: ✨ Feat

#129 chore: production 배포 환경 및 CD 스크립트 작성
  .github/workflows/DeployToProd.yml
  infra/production/.gitkeep
  infra/production/docker/docker-compose.yml
  infra/production/docker/kafka-docker-compose.yml
  infra/production/nginx/nginx.conf
Labels: 🧹 Chore

#124 feat : OCR 결과 폴링
  src/main/java/depromeet/onepiece/feedback/command/application/exception/FeedbackCommandExceptionCode.java
  src/main/java/depromeet/onepiece/feedback/command/application/exception/GetOCRResultFailedException.java
  src/main/java/depromeet/onepiece/feedback/command/application/exception/OCRResultNotFoundException.java
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/S3OCRJsonPoller.java
Labels: ✨ Feat

#132 refactor : ChatGPT 요청 프롬프트, jsonSchema DB에 저장 후 사용
  src/main/java/depromeet/onepiece/feedback/command/application/ChatGPTConstants.java
  src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandFacadeService.java
  src/main/java/depromeet/onepiece/feedback/domain/ChatGPTConstants.java
  src/main/java/depromeet/onepiece/feedback/query/application/ChatGPTConstantsProvider.java
  src/main/java/depromeet/onepiece/feedback/query/application/exception/ChatGPTConstantNotFoundException.java
  src/main/java/depromeet/onepiece/feedback/query/application/exception/FeedbackQueryExceptionCode.java
  src/main/java/depromeet/onepiece/feedback/query/infrastructure/ChatGPTConstantsRepository.java
Labels: ♻️ Refactor
