Repository depromeet/critix-server, pull requests merged in 2025-02, with the labels that each got.

#8 chore: 스웨거 세팅
  build.gradle
  src/main/java/depromeet/onepiece/common/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: 🧹 Chore

#10 chore: 개발 서버 docker compose 기반 환경 구축 및 배포 파이프라인 작성
  .github/workflows/BuilldCheck.yml
  .github/workflows/DeployToDev.yml
  Dockerfile
  infra/development/docker-compose.yml
  infra/production/.gitkeep
Labels: 🧹 Chore

#14 feat : 글로벌 에러 핸들러 설정 (#13)
  src/main/java/depromeet/onepiece/common/error/CustomResponse.java
  src/main/java/depromeet/onepiece/common/error/GlobalControllerAdvice.java
  src/main/java/depromeet/onepiece/common/error/GlobalErrorCode.java
  src/main/java/depromeet/onepiece/common/error/GlobalException.java
Labels: ✨ Feat

#16 feat : entity 설계
  build.gradle
  src/main/java/depromeet/onepiece/common/config/MongoConfig.java
  src/main/java/depromeet/onepiece/common/domain/BaseTimeDocument.java
  src/main/java/depromeet/onepiece/feedback/domain/AdditionalChat.java
  src/main/java/depromeet/onepiece/feedback/domain/EvaluationItem.java
  src/main/java/depromeet/onepiece/feedback/domain/EvaluationType.java
  src/main/java/depromeet/onepiece/feedback/domain/Feedback.java
  src/main/java/depromeet/onepiece/feedback/domain/FeedbackPerPage.java
  src/main/java/depromeet/onepiece/feedback/domain/FeedbackPerProject.java
  src/main/java/depromeet/onepiece/feedback/domain/OverallEvaluation.java
  src/main/java/depromeet/onepiece/portfolio/domain/Image.java
  src/main/java/depromeet/onepiece/portfolio/domain/Portfolio.java
  src/main/java/depromeet/onepiece/user/domain/OAuthProviderType.java
  src/main/java/depromeet/onepiece/user/domain/User.java
Labels: ✨ Feat

#18 feat : mongodb 설정 #17
  infra/development/docker-compose.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: ✨ Feat

#19 feat: Spring Security 설정 및 Google OAuth2 설정
  build.gradle
  src/main/java/depromeet/onepiece/common/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: ✨ Feat

#22 feat : ChatGPT API 연동
  .gitignore
  build.gradle
  src/main/java/depromeet/onepiece/common/config/PropertiesConfig.java
  src/main/java/depromeet/onepiece/common/config/RestClientConfig.java
  src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandService.java
  src/main/java/depromeet/onepiece/feedback/command/application/exception/FeedbackCommandExceptionCode.java
  src/main/java/depromeet/onepiece/feedback/command/domain/FeedbackCommandRepository.java
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/ChatGPTClient.java
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/ChatGPTConstants.java
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/ChatGPTProperties.java
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/ChatGPTService.java
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/FeedbackCommandRepositoryImpl.java
  src/main/java/depromeet/onepiece/feedback/command/presentation/FeedbackCommandController.java
  src/main/java/depromeet/onepiece/feedback/command/presentation/request/ChatGPTRequest.java
  src/main/java/depromeet/onepiece/feedback/command/presentation/response/ChatGPTResponse.java
  src/main/java/depromeet/onepiece/feedback/command/presentation/response/OverallFeedbackResponse.java
  src/main/java/depromeet/onepiece/feedback/command/presentation/response/ProjectFeedbackResponse.java
  src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryService.java
  src/main/java/depromeet/onepiece/feedback/query/application/exception/FeedbackQueryExceptionCode.java
  src/main/java/depromeet/onepiece/feedback/query/domain/FeedbackQueryRepository.java
  src/main/java/depromeet/onepiece/feedback/query/infrastructure/FeedbackQueryRepositoryImpl.java
  src/main/java/depromeet/onepiece/feedback/query/presentation/FeedbackQueryController.java
  src/main/java/depromeet/onepiece/feedback/query/presentation/request/.gitkeep
  src/main/java/depromeet/onepiece/feedback/query/presentation/response/.gitkeep
  src/main/java/depromeet/onepiece/portfolio/domain/exception/PortfolioDomainExceptionCode.java
  src/main/resources/application.yml
Labels: ✨ Feat

#25 fix: httpclient5 버전 이슈 픽스 및 ErrorCode 인터페이스 도입
  build.gradle
  src/main/java/depromeet/onepiece/OnepieceApplication.java
  src/main/java/depromeet/onepiece/common/.gitkeep
  src/main/java/depromeet/onepiece/common/config/PropertiesConfig.java
  src/main/java/depromeet/onepiece/common/config/SecurityConfig.java
  src/main/java/depromeet/onepiece/common/error/CustomResponse.java
  src/main/java/depromeet/onepiece/common/error/ErrorCode.java
  src/main/java/depromeet/onepiece/common/error/GlobalErrorCode.java
  src/main/java/depromeet/onepiece/common/error/GlobalException.java
  src/main/java/depromeet/onepiece/payment/command/application/PaymentCommandService.java
  src/main/java/depromeet/onepiece/payment/command/application/exception/PaymentCommandExceptionCode.java
  src/main/java/depromeet/onepiece/payment/command/domain/PaymentCommandRepository.java
  src/main/java/depromeet/onepiece/payment/command/infrastructure/PaymentCommandRepositoryImpl.java
  src/main/java/depromeet/onepiece/payment/command/presentation/PaymentCommandController.java
  src/main/java/depromeet/onepiece/payment/command/presentation/request/.gitkeep
  src/main/java/depromeet/onepiece/payment/command/presentation/response/.gitkeep
  src/main/java/depromeet/onepiece/payment/domain/Payment.java
  src/main/java/depromeet/onepiece/payment/domain/exception/PaymentDomainExceptionCode.java
  src/main/java/depromeet/onepiece/payment/query/application/PaymentQueryService.java
  src/main/java/depromeet/onepiece/payment/query/application/exception/PaymentQueryExceptionCode.java
  src/main/java/depromeet/onepiece/payment/query/domain/PaymentQueryRepository.java
  src/main/java/depromeet/onepiece/payment/query/infrastructure/PaymentQueryRepositoryImpl.java
  src/main/java/depromeet/onepiece/payment/query/presentation/PaymentQueryController.java
  src/main/java/depromeet/onepiece/payment/query/presentation/request/.gitkeep
  src/main/java/depromeet/onepiece/payment/query/presentation/response/.gitkeep
Labels: ⚒️ Fix, ♻️ Refactor

#26 feat: object storage 연동 및 파일 업로드 기능 구현
  build.gradle
  src/main/java/depromeet/onepiece/common/config/FileUploadConfig.java
  src/main/java/depromeet/onepiece/common/utils/EncryptionUtil.java
  src/main/java/depromeet/onepiece/file/command/application/FileUploadService.java
  src/main/java/depromeet/onepiece/file/command/application/FileUploader.java
  src/main/java/depromeet/onepiece/file/command/domain/FileDocumentRepository.java
  src/main/java/depromeet/onepiece/file/command/exception/FileCommandExceptionCode.java
  src/main/java/depromeet/onepiece/file/command/exception/FileConvertErrorException.java
  src/main/java/depromeet/onepiece/file/command/exception/FileUploadFailedException.java
  src/main/java/depromeet/onepiece/file/command/infrastructure/FileDocumentMongoRepository.java
  src/main/java/depromeet/onepiece/file/command/infrastructure/FileDocumentRepositoryImpl.java
  src/main/java/depromeet/onepiece/file/command/infrastructure/ObjectStorageFileUploader.java
  src/main/java/depromeet/onepiece/file/command/infrastructure/PresignedUrlProperties.java
  src/main/java/depromeet/onepiece/file/command/presentation/FileUploadController.java
  src/main/java/depromeet/onepiece/file/command/presentation/response/PresignedUrlResponse.java
  src/main/java/depromeet/onepiece/file/domain/FileDocument.java
  src/main/java/depromeet/onepiece/file/domain/FileType.java
  src/main/resources/application.yml
Labels: ✨ Feat

#29 chore : 이슈 템플릿 정리
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: 🧹 Chore

#30 fix: 스웨거 서버 URL 불일치로 인한 CORS 이슈 픽스
  src/main/java/depromeet/onepiece/common/config/SwaggerConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ⚒️ Fix

#32 refactor: 첨부파일 응답에 파일 식별자와 파일 명을 추가
  src/main/java/depromeet/onepiece/file/command/application/FileUploadService.java
  src/main/java/depromeet/onepiece/file/command/application/FileUploader.java
  src/main/java/depromeet/onepiece/file/command/domain/FileDocumentRepository.java
  src/main/java/depromeet/onepiece/file/command/infrastructure/FileDocumentRepositoryImpl.java
  src/main/java/depromeet/onepiece/file/command/infrastructure/ObjectStorageFileUploader.java
  src/main/java/depromeet/onepiece/file/command/presentation/FileUploadController.java
  src/main/java/depromeet/onepiece/file/command/presentation/response/FileUploadResponse.java
  src/main/java/depromeet/onepiece/file/command/presentation/response/PresignedUrlResponse.java
Labels: ♻️ Refactor
