Repository depromeet/critix-server, pull requests merged in 2025-04, with the labels that each got.

#139 fix: production 배포 파이프라인 버그 수정
  .github/workflows/DeployToProd.yml
Labels: 🧹 Chore, ⚒️ Fix

#150 fix : 전체 피드백 반환 로직 수정
  src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryFacadeService.java
Labels: ⚒️ Fix

#153 fix : presigned URL 생성 경로 오류 수정, ocr 결과 호출
  src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandFacadeService.java
  src/main/java/depromeet/onepiece/feedback/command/infrastructure/S3OCRJsonPoller.java
  src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryFacadeService.java
  src/main/java/depromeet/onepiece/file/command/application/PresignedUrlGenerator.java
Labels: ⚒️ Fix

#155 fix: production CORS 이슈 픽스
  src/main/java/depromeet/onepiece/common/config/SecurityConfig.java
Labels: ⚒️ Fix

#158 fix: CORS 이슈 및 도커 이미지 삭제 워크플로 개선
  .github/workflows/DeployToProd.yml
Labels: ⚒️ Fix

#163 feat : userName 전달, 로깅 추가
  src/main/java/depromeet/onepiece/common/eventsourcing/consumer/GPTEventConsumer.java
  src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandFacadeService.java
Labels: ✨ Feat

#165 fix : 프로젝트 대표 이미지 전달
  src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandFacadeService.java
  src/main/java/depromeet/onepiece/feedback/domain/ProjectEvaluation.java
  src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryFacadeService.java
Labels: ⚒️ Fix

#172 fix : 이미지 경로 수정
  src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryFacadeService.java
Labels: ⚒️ Fix

#181 feat : 디자이너 포트폴리오 필터링 로직 구현
  src/main/java/depromeet/onepiece/feedback/command/application/FeedbackCommandFacadeService.java
  src/main/java/depromeet/onepiece/feedback/command/application/exception/FeedbackCommandExceptionCode.java
  src/main/java/depromeet/onepiece/feedback/domain/ChatGPTConstants.java
  src/main/java/depromeet/onepiece/feedback/query/application/ChatGPTConstantsProvider.java
  src/main/java/depromeet/onepiece/file/command/application/ObjectStorageFileUploader.java
  src/main/java/depromeet/onepiece/file/command/exception/FileCommandExceptionCode.java
  src/main/java/depromeet/onepiece/file/command/exception/FileFilteringException.java
Labels: ✨ Feat

#182 feat: Grafana Alloy 기반 모니터링 시스템 구축
  .github/workflows/DeployToProd.yml
  build.gradle
  infra/development/docker/docker-compose.yml
  infra/development/docker/kafka-docker-compose.yml
  infra/development/docker/monitoring-docker-compose.yml
  monitoring/alloy/config.alloy
  monitoring/prometheus/prometheus.rules.yml
  monitoring/prometheus/prometheus.yml
  src/main/resources/logback-spring.xml
Labels: ✨ Feat

#188 fix : 피드백 반환 최신순 정렬
  src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryFacadeService.java
  src/main/java/depromeet/onepiece/feedback/query/application/FeedbackQueryService.java
  src/main/java/depromeet/onepiece/feedback/query/infrastructure/FeedbackQueryRepository.java
  src/main/java/depromeet/onepiece/feedback/query/infrastructure/FeedbackQueryRepositoryImpl.java
Labels: ⚒️ Fix
